### ISSUE TITLE
run docker Image on Synology NAS

### ISSUE THREAD

**Issue by lucas2350d** [jusito/docker-ttt#11]
Hey jusito, 
I would like to run your Docker image on my NAS. I make the following settings:
Set a volume folder to /home/steam/serverfiles
enter my workshop ID and API key, set server name and password and install CSS and HL2

after a few seconds the following problem appears:

mkdir: cannot create directory ‘/home/steam/serverfiles/garrysmod’: Permission denied
and other Permission errors in /home

Can you help me?
Thanks

**Comment by jusito** [comment]
Hey Lucas,
can you provide me the exact command you used, just replace secrets with dummy value?

**Comment by lucas2350d** [comment]
Thanks for replying, in the meantime I got the server started once with this command:

 docker run -d \
 -p 27015:27015/udp \
 -e SERVER_PORT=27015 \
 -e INSTALL_CSS=true \
 -e WORKSHOP_COLLECTION_ID=###### \
 -e SERVER_NAME="#####" \
 -e SERVER_PASSWORD="#####" \
 -e SERVER_DEFAULT_MAP="ttt_minecraft_b5" \
 -v TTTDev:/home/steam/serverfiles \
 -p 27015:27015/tcp \
 -e SERVER_RCON_PASSWORD="########" \
 --name "MyTTTServer" \
 jusito/docker-ttt:latest
 
now the start is no longer possible with the following log error message:
checking GitHub module install_stats.sh...OK
checking GitHub module install_steamcmd.sh...OK
checking GitHub module lgsm...ERROR
rm: cannot remove 'lgsm': Is a directory
removing module lgsm...FAIL

after that the Container crashed

**Comment by jusito** [comment]
If the server is starting only the first time but not the second, probably an update broke it.
The linuxgsm version in docker hub is outdated, in the first boot it will just install itself and start but doesn't check for an update. At every later start it checks if lgsm is already installed and if so perform an update. I have to admit I thought this bug is already fixed, because was issue #9 .

You can recreate the image locally, or you wait until I push a new one.

**Comment by lucas2350d** [comment]
Ok thanks for the answer
So it is not fixed even in the Develop version?
Is there an easy way for me to take this update query out?

**Comment by jusito** [comment]
yes if you use `docker exec -it CONTAINER details` you will see that linuxgsm changes the location of the cfg.

You are welcome.
